# Model configuration
model:
  num_states: 5
  state_dim: 16
  obs_dim: 20
  transition:
    hidden_dims: [32]
    activation: tanh
    dropout: 0.0
  emission:
    hidden_dims: [32]
    activation: tanh
    dropout: 0.0
    std_init: 0.5
    std_min: 0.1
    std_max: 2.0
  inference:
    rnn_hidden_dim: 32
    rnn_num_layers: 1
    hidden_dims: [32]
    dropout: 0.0
  gumbel:
    temperature_init: 10.0
    temperature_min: 0.5
    temperature_anneal_rate: 0.9995
  regularization:
    kl_weight_init: 0.0001
    kl_weight_max: 0.1
    kl_anneal_rate: 1.002

# Data configuration
data:
  num_sequences_train: 1000
  num_sequences_val: 200
  seq_length: 50
  num_true_states: 5
  obs_dim: 20

  transition_bias: 0.55  # Very low - states change frequently (almost random walk)
  emission_overlap: 0.9  # Extreme overlap - states almost indistinguishable
  emission_noise_scale: 3.0  # Very high noise - SNR is terrible
  state_persistence_prob: 0.35  # 35% random jumps - breaks Markov assumption badly
  rare_state_prob: 0.05  # Some states appear only 5% as often as others

  seed: 42
  num_workers: 0

# Training configuration
training:
  batch_size: 64
  learning_rate: 0.001
  num_epochs: 300
  grad_clip: 0.5
  device: cpu
  scheduler:
    enabled: true
    patience: 20
    factor: 0.7
    min_lr: 0.00001
  logging:
    val_interval: 5
    use_wandb: true
    project_name: dssm-categorical
    run_name: null
